services:
  mongodb:
    image: mongo:7
    container_name: rescuenet-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: disasterDB
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: rescuenet-backend
    ports:
      - "5001:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/disasterDB
      JWT_SECRET: supersecretjwtkey
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5001/api
    container_name: rescuenet-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
    depends_on:
      - backend

volumes:
  mongo_data:
