[jenkins]
jenkins-server ansible_host=JENKINS_PUBLIC_IP ansible_user=ubuntu

[app_servers]
app-server ansible_host=APP_SERVER_PUBLIC_IP ansible_user=ubuntu

[monitoring]
monitoring-server ansible_host=MONITORING_PUBLIC_IP ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
